"""Updated tables

Revision ID: 731704eaa6b1
Revises: 2fd47300454b
Create Date: 2025-06-02 10:13:23.675396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '731704eaa6b1'
down_revision = '2fd47300454b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_name', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_column('file_name')

    # ### end Alembic commands ###
