"""added folder_name to project

Revision ID: eaa6fcd0d9b3
Revises: 731704eaa6b1
Create Date: 2025-06-07 15:18:09.646528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eaa6fcd0d9b3'
down_revision = '731704eaa6b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('folder_name', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_column('folder_name')

    # ### end Alembic commands ###
